### PR TITLE
Selectable bbb version

### LINKED ISSUE #200: Selectable BBB version
**Is your feature request related to a problem? Please describe.**
I can not install [fairblue](https://git.fairkom.net/chat/fairblue) because, it will not works with BBB 2.3.4 but with BBB 2.3.0

**Describe the solution you'd like**
Create new variable `bbb_version` to set manuell another version and create a new rule in [tasks/repositories.yml](https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/bbb/2.3/tasks/repositories.yml).

e.g. set apt repository from `deb https://ubuntu.bigbluebutton.org/bionic-230/ bigbluebutton-bionic main` to `deb https://ubuntu.bigbluebutton.org/bionic-230-2.3.0 bigbluebutton-bionic main`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by wilkis3**
Fixed #200 

Some product like [fairblue](https://git.fairkom.net/chat/fairblue) works **not** for the newest BigBlueButton release anytimes.

The copy task is needed to overwrite content. (see [ansible Issue #58386](https://github.com/ansible/ansible/issues/58386#issuecomment-505888418))

### CODE REVIEW

**Comment by BrutalBirdie** [comment]
Nice, test deploying right now.
I guess running `bbb_version: 2.3.3` with `bbb_state: "latest"` will be no problem since the apt repo will always be the latest version since its a fixed version.

**Comment by BrutalBirdie** [comment]
First error:
```
TASK [ansible-role-bigbluebutton : add bigbluebutton.org repo key] **************************************************************************
fatal: [meet.bbb.ansibletest.safeserver-support.de]: FAILED! => {"changed": false, "msg": "Failed to download key at https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>"}
```

**Comment by BrutalBirdie** [comment]
OK now I ignored the SSL cert validity to test this and got this error:
```
TASK [ansible-role-bigbluebutton : add Bionic dependency apt repositories] ******************************************************************
failed: [meet.bbb.ansibletest.safeserver-support.de] (item=ppa:bigbluebutton/support) => {"ansible_loop_var": "item", "changed": false, "item": "ppa:bigbluebutton/support", "msg": "Failed to update apt cache: E:The repository 'https://ubuntu.bigbluebutton.org/bionic-230-2.3.3 bigbluebutton-bionic Release' does not have a Release file."}
failed: [meet.bbb.ansibletest.safeserver-support.de] (item=ppa:rmescandon/yq) => {"ansible_loop_var": "item", "changed": false, "item": "ppa:rmescandon/yq", "msg": "Failed to update apt cache: E:The repository 'https://ubuntu.bigbluebutton.org/bionic-230-2.3.3 bigbluebutton-bionic Release' does not have a Release file."}
failed: [meet.bbb.ansibletest.safeserver-support.de] (item=ppa:certbot/certbot) => {"ansible_loop_var": "item", "changed": false, "item": "ppa:certbot/certbot", "msg": "Failed to update apt cache: E:The repository 'https://ubuntu.bigbluebutton.org/bionic-230-2.3.3 bigbluebutton-bionic Release' does not have a Release file."}
```

**Comment by wilkis3** [comment]
> First error:
> 
> ```
> TASK [ansible-role-bigbluebutton : add bigbluebutton.org repo key] **************************************************************************
> fatal: [meet.bbb.ansibletest.safeserver-support.de]: FAILED! => {"changed": false, "msg": "Failed to download key at https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>"}
> ```
> 
> ```
> Common Name (CN)	ubuntu.bigbluebutton.org
> Organization (O)	<Not Part Of Certificate>
> Organizational Unit (OU)	<Not Part Of Certificate>
> Common Name (CN)	R3
> Organization (O)	Let's Encrypt
> Organizational Unit (OU)	<Not Part Of Certificate>
> Issued On	Saturday, April 17, 2021 at 4:22:50 AM
> Expires On	Friday, July 16, 2021 at 4:22:50 AM
> SHA-256 Fingerprint	77 FE 69 7A F3 11 94 73 22 D1 16 43 5E 85 02 36
> 54 DC 1C AE 9C 02 55 37 57 C0 F1 C0 77 08 DF 15
> SHA-1 Fingerprint	E2 6B 92 07 8D 9F 48 3B C0 F8 68 10 5F 37 25 09
> 2A CF 0E 3F
> ```
> 
> Hmmmm it's expired...
> 
> https://crt.sh/?q=ubuntu.bigbluebutton.org
> https://crt.sh/?id=4387940468

May you steped in a no valid TLS certificat time slot. Can you try it again?

**Comment by BrutalBirdie** [comment]
This is a nice addition we should get this merged @Davka @crosscodr

**Comment by crosscodr** [comment]
Hi @wilkis3,
please consider doing a rebase instead of merging bbb/2.3 branch.
Its much easier to see the actual changes then.

**Comment by wilkis3** [comment]
> Hi @wilkis3,
> please consider doing a rebase instead of merging bbb/2.3 branch.
> Its much easier to see the actual changes then.

Okay, I will do it the next time. There was a merge conflict in the README.md.

**Comment by wilkis3** [comment]
> > Hi @wilkis3,
> > please consider doing a rebase instead of merging bbb/2.3 branch.
> > Its much easier to see the actual changes then.
> 
> Okay, I will do it the next time. There was a merge conflict in the README.md.

@crosscodr looks the pull request good?

**Review by crosscodr — CHANGES_REQUESTED** [review]
Hi @wilkis3,
this looks quite good to me.
Can you implement a "file state=absent" task for ubuntu_bigbluebutton_org_bionic_230.list in case of `bbb_version is undefined`?
I wonder if we need something similar for the apt_repository task, so that one can cleanly switch from `bbb_version is undefined` to `bbb_version is defined`, and back.
Got, what I mean?

**Comment by BrutalBirdie** [comment]
Moved this PR to #266 due to inactivity

**Pull request closed without merging**
