### PR TITLE
Added bbb_docker_python_version variable

### PR DESCRIPTION
**Pull request by simoncolincap**
Fixes https://github.com/ebbba-org/ansible-role-bigbluebutton/issues/371 by setting a specific version for the Docker Python package.

### CODE REVIEW

**Comment by BrutalBirdie** [comment]
Hmm something is up the full deployment test.
Need to check that out.

**Comment by cherbst** [comment]
Having the same problem

**Comment by GUFFMHRZ** [comment]
Same here, Nodes get thrown out of monitoring after running the role

**Comment by berott** [comment]
is it correct, that this PR merges into bbb/2.6? I have the same problem with bbb/2.7

**Comment by BrutalBirdie** [comment]
> is it correct, that this PR merges into bbb/2.6? I have the same problem with bbb/2.7

Oh! Did not even notice that. Yes right, should actually be merged against the `master` branch.
I have adjusted that.

**Comment by BrutalBirdie** [comment]
The full deployment test still fails:
https://github.com/ebbba-org/ansible-role-bigbluebutton/actions/runs/7182177988/job/20047264408?pr=372#step:6:3932

I will check this out now.

**Comment by BrutalBirdie** [comment]
@cherbst and @GUFFMHRZ 
I assume you are using the:
```yaml
bbb_monitoring_all_in_one_enable: true
```
Variable.

Are you also setting:

```yaml
bbb_monitoring_all_in_one_grafana: false
bbb_monitoring_all_in_one_prometheus: false
bbb_monitoring_external: true
```

Or what do you people set?
Because I just run with this PR diff applied with no issues.

**Comment by berott** [comment]
I use the following monitoring-configuration:
```
    bbb_monitoring_all_in_one_enable: true
    bbb_monitoring_all_in_one_grafana: false
    bbb_monitoring_all_in_one_prometheus: false
    bbb_monitoring_recordings_from_disk: false
    bbb_monitoring_external: true
    bbb_monitoring_htpasswd_user: "{{bbb_mon_user}}"
    bbb_monitoring_htpasswd: "{{bbb_mon_pass}}"
    bbb_monitoring_systemd_enable: false
```

Temporary I changed the docker-version manually (based on the information of this PR), after that it runs correctly:

```
- name: Install python docker packages
  pip:
    name:
      - docker==6.1.3
      - docker-compose=={{ bbb_docker_compose_version }}
    state: "{{ bbb_state }}"
```

**Comment by GUFFMHRZ** [comment]
> @cherbst and @GUFFMHRZ I assume you are using the:
> 
> ```yaml
> bbb_monitoring_all_in_one_enable: true
> ```
> 
> Variable.
> 
> Are you also setting:
> 
> ```yaml
> bbb_monitoring_all_in_one_grafana: false
> bbb_monitoring_all_in_one_prometheus: false
> bbb_monitoring_external: true
> ```
> 
> Or what do you people set? Because I just run with this PR diff applied with no issues.

Hi, 
we're running:

- name: Install python docker packages
  pip:
    name:
      - docker=={{ bbb_docker_python_version }}
      - docker-compose=={{ bbb_docker_compose_version }}
    state: "{{ bbb_state }}"

# https://pypi.org/project/docker/#history
bbb_docker_python_version: 6.1.3
# https://pypi.org/project/docker-compose/#history
bbb_docker_compose_version: 1.29.2

and 

bbb_monitoring_all_in_one_enable: yes
bbb_monitoring_all_in_one_grafana: false
bbb_monitoring_all_in_one_prometheus: false
bbb_monitoring_exporter_version: latest
bbb_monitoring_external: true

**Comment by GUFFMHRZ** [comment]
> Temporary I changed the docker-version manually (based on the information of this PR), after that it runs correctly:
> 
> ```yaml
> - name: Install python docker packages
>   pip:
>     name:
>       - docker==6.1.3
>       - docker-compose=={{ bbb_docker_compose_version }}
>     state: "{{ bbb_state }}"
> ```

This did not help us

**Comment by cherbst** [comment]
> @cherbst and @GUFFMHRZ I assume you are using the:
> 
> ```yaml
> bbb_monitoring_all_in_one_enable: true
> ```
> 
> Variable.
> 
> Are you also setting:
> 
> ```yaml
> bbb_monitoring_all_in_one_grafana: false
> bbb_monitoring_all_in_one_prometheus: false
> bbb_monitoring_external: true
> ```
> 
> Or what do you people set? Because I just run with this PR diff applied with no issues.

What I meant to say was that this PR fixes the problem in #371, not that I have a problem with this PR.
We have 
```yaml
bbb_monitoring_all_in_one_enable: true
```
and none of the other monitoring settings.

**Comment by BrutalBirdie** [comment]
Sorry for not doing anything here for so long.
But now I finally hit this rock again :D

Came back to the issue and starting thinking.
We should switch to [community.docker.docker_compose_v2](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html)

Since it only needs:
```
Docker CLI with Docker compose plugin 2.18.0 or later

    PyYAML if [definition](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html#ansible-collections-community-docker-docker-compose-v2-module-parameter-definition) is used
```

and the pip package can be gone.

Thoughts?

**Pull request closed without merging**
