### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by juju4**
manual install of wheel to avoid "error: invalid command 'bdist_wheel'"

### CODE REVIEW

**Comment by juju4** [comment]
Anything needed here?
would be really nice to have it merge so it can re-validate other PRs.

**Comment by juju4** [comment]
any feedback?
there are non-travis config related fixes that I would prefer committed before working on the github action equivalent.

**Comment by anadahz** [comment]
@juju4 thanks a lot for working on this.

This PR should be merged as it is very important to have CI tests to this role.

**Comment by BrutalBirdie** [comment]
PR Stale and not ready for bbb 2.3
Closing for now.
---
Also I was told some issues with the new plans around travis and @davidmehren wanted to take a look at this to do this via github actions.

**Pull request closed without merging**
