### PR TITLE
Revert "Path to images has changed"

### PR DESCRIPTION
**Pull request by einhirn**
This reverts commits af9d3f5ba024fd4f109cd3a80e721ef95bd05328 and 8af8705d7eba3ae519389c549683f14589ea474c.

### CODE REVIEW

**Comment by BrutalBirdie** [comment]
Is this a Problem for 2.6/2.5? A little explanation in the PR description would be helpful :/
Also could you please fix the ansible-linting warning, which got brought back by the revert? 😬

**Comment by einhirn** [comment]
I referenced another Commit which changed "bbb_nginx_root" in defaults: https://github.com/ebbba-org/ansible-role-bigbluebutton/commit/5793945e840e278b9bb8d1adfce90169a8aaa7f9#comments

The commits I wanted to revert modified paths using "bbb_nginx_root" by adding the new part `assets/` there, which duplicated the effect.

Re: Linting: I thought I was careful enough to keep the syntax intact and the checks seem to have passed...

**Comment by einhirn** [comment]
Sneaky little whitespace... I thought I caught all of them before. Now I hope I really got em all.

**Review by lassgutsein — APPROVED** [review]
Tested the changes and it fixed the upcoming problem(missing destination).

**Comment by lassgutsein** [comment]
I have to revert my approval. Sorry was to hasty :grimacing: 
Since mid deployment it failed with:

```
2023-04-20 15:03:11,644 p=31395 u=lassgutsein n=ansible | TASK [ansible-role-bigbluebutton : Set default presentation] ***********************************************************************************************
2023-04-20 15:03:14,013 p=31395 u=lassgutsein n=ansible | fatal: [bbb-dev01.bbb.ansibletest.safeserver-support.de]: FAILED! => {"changed": false, "checksum": "baaf75650086ec69a5ac8b250e76468974c96c68", "msg": "Destination directory /var/www/bigbluebutton-default/assets does not exist"}

```
So yes the default is:
[src](https://github.com/bigbluebutton/bigbluebutton/blob/5aef1b817107e89e223816a11aa93200139efd1c/build/packages-template/bbb-html5/bigbluebutton.nginx#L10)
```yaml
server {
     listen   80;
     listen [::]:80;
     server_name  192.168.0.103;

     access_log  /var/log/nginx/bigbluebutton.access.log;

        # BigBlueButton assets and static content.
        location / {
          root   /var/www/bigbluebutton-default/assets;
          index  index.html index.htm;
          expires 1m;
        }

        # Include specific rules for record and playback
        include /etc/bigbluebutton/nginx/*.nginx; # an overriding set of files, possibly present
}

```
But for some reason this folder does not exist by default.
So it should be ensured this folder exists.

**Comment by BrutalBirdie** [comment]
@einhirn 
For whatever reason only a ansible-lint check was started and not a deploy test. Not sure why, need to investigate.
Buy this sounds like an issue :)

**Comment by BrutalBirdie** [comment]
had to close and re-open this PR so the pipeline is fixed now :)

**Comment by lassgutsein** [comment]
Since the deployment test does not cover a custom presentation this issue doesn't exist in the pipeline.

To fix it.
I added the following block of code before the default presentation: 

https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/29df9142a40fb52bbb06616d5c22022cff6d963a/tasks/config.yml#L159-L167

```yaml
- name: Ensure bbb_nginx_root directory exists
  ansible.builtin.file:
    path: "{{ bbb_nginx_root }}"
    state: directory
    mode: '0755'

```

**Comment by BrutalBirdie** [comment]
Just looked into @lassgutsein work since I set next to him ;)
We deployed a 2.5 BBB with this change 🙄 brb with a new test result.

**Comment by lassgutsein** [comment]
Hello friends,

it worked with version 2.6... as expected :D

**Pull request merged**
