### PR TITLE
Restore bbb_nginx_listen_https option

### PR DESCRIPTION
**Pull request by znerol**
First introduced in #88 / 2c4385b4 but somehow this option got lost along the way.

### CODE REVIEW

**Comment by defnull** [comment]
While this probably works, it is a very strange or hard-to-read way to modify the nginx config blocks. Could this be refactored to be more clear?

**Comment by BrutalBirdie** [comment]
Ahh, thanks for reporting.
I believe it would be even better to make all template files user overwrite-able.

Also what @defnull said, a refactoring would be nice.

**Comment by defnull** [comment]
Can we just drop HTTP (without S) support? It's 2022 and certificates are free. I'm not sure if BBB even works properly over HTTP as many additional restrictions for XHR or cookies apply. BBB lists SSL under [minimum server requirements](https://docs.bigbluebutton.org/2.5/install.html#minimum-server-requirements)

**Comment by mmv-ru** [comment]
@defnull
 I got your reasons and decide to reconfigure reverseproxy to allow passtrough /.well-known/acme-challenge/ to application host. It allow get letsencrypt work in parallel on reverseproxy and on application host.
But my setup is reverseproxy behimd nat, which share single public IP between multiple domains (applications). :-)

**Pull request merged**
