### PR TITLE
avoid some ansible warnings

### PR DESCRIPTION
**Pull request by crosscodr**
additionally some syntactic sugar

### CODE REVIEW

**Review by anadahz — APPROVED** [review]

**Comment by BrutalBirdie** [comment]
Note to me, setup yamllint and ansiblelint for GitHub.
Please check your PR against both.

**Comment by crosscodr** [comment]
yamllint and ansible-lint doesn't complain about anything in the files, changed by this PR

**Comment by BrutalBirdie** [comment]
> yamllint and ansible-lint doesn't complain about anything in the files, changed by this PR

All good just wanted to be sure, I did not test it against both linter, thanks for doing so.

**Comment by crosscodr** [comment]
Sorry, my comment wasn't meant to be offensive at all :)
It's always good to check twice.

**Review by Davka — APPROVED** [review]

**Review by n0emis — APPROVED** [review]

**Pull request merged**
