### PR TITLE
leverage systemd for some hardening

### PR DESCRIPTION
**Pull request by juju4**
for freeswitch, kurento, red5, bbb-web, bbb-html5
use a systemd override file with seccomp, cgroups protection features.

no service impact during my testing

### CODE REVIEW

**Comment by gretel** [comment]
@juju4 thanks, can you fix the conflict?

**Comment by juju4** [comment]
done.
Likely need more careful review when bbb available on 18.04 and 20.04

**Comment by gretel** [comment]
> done.
> Likely need more careful review when bbb available on 18.04 and 20.04

thanks! afair the official targeting is on `22.04` ...

**Comment by BrutalBirdie** [comment]
PR Stale not ready for bbb 2.3
Also I did quite the improvements with apparmor thanks to infra.run.
Could you check that out @juju4 ?

Closing for now since stale - awaiting feedback.

**Pull request closed without merging**
